### ISSUE TITLE
custom_updater.update_all not updating from component_urls

### ISSUE THREAD

**Issue by pnbruckner** [custom-components/custom_updater#42] opened 2018-10-02 13:09 UTC
**Version of the custom_component**
3.1.2

**Describe the bug**
~https://github.com/ludeeus/pyupdate/blob/e3c8031081fd43ef482a60190083eba9ec535547/pyupdate/ha_custom/custom_components.py#L66-L72 is only using the first element of the returned list, so the components from component_urls are being ignored and not updated. This function should be looping through the returned list.~

EDIT: I read the code wrong. The root of the problem may not be in these particular code lines. But components from component_urls are not getting updated, even though they are listed as having updates.

**log**

```
Add your logs here.
```

**Comment by pnbruckner** [comment] 2018-10-02 13:11
Although I haven't tried them yet, it looks like the same issue is in the code for cards and python_scripts as well.

**Comment by WildeRNS** [comment] 2018-10-02 13:18
can confirm - custom cards not updates...

**Comment by pnbruckner** [comment] 2018-10-02 14:08
This is a strange one. I just went through and "manually" tried the update by calling the individual pieces in pyupdate.ha_custom.custom_components.update_all, and _it worked!_ But if I try calling the custom_updater.update_all service, it doesn't. FWIW, here are the steps I used to run it "manually":

```
pi@raspberrypi:/home/homeassistant/.homeassistant $ sudo -u homeassistant -s -H
homeassistant@raspberrypi:~/.homeassistant $ source /srv/homeassistant/bin/activate
(homeassistant) homeassistant@raspberrypi:~/.homeassistant $ python
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170124] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyupdate.ha_custom import custom_components
>>> updates = custom_components.get_sensor_data('/home/homeassistant/.homeassistant', False, ['https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json'])[0]['has_update']
>>> updates
['device_tracker.life360']
>>> custom_components.upgrade_single('/home/homeassistant/.homeassistant', 'device_tracker.life360', ['https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json'])
>>> updates = custom_components.get_sensor_data('/home/homeassistant/.homeassistant', False, ['https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json'])[0]['has_update']
>>> updates
[]
```
When I run the service from the frontend Services page, I get no errors, and I don't see anything useful in home-assistant.log. It just shows the service being called, and immediately a state_changed event for sensor.custom_component_tracker, where it clearly shows the custom component was not updated.

**Comment by ludeeus** [comment] 2018-10-02 14:13
Both this issue, and this one <https://github.com/ludeeus/pyupdate/issues/1> are the only thing I'm doing today both have my full attention.

**Comment by ludeeus** [comment] 2018-10-02 14:47
FFS... okei...
found the issue.
Pushing a fix for it now 🤦‍♂️

**Comment by ludeeus** [comment] 2018-10-02 15:05
@pnbruckner @WildeRNS Version 3.1.3 that fixes this issue are now available.
I also added some logging:
```
2018-10-02 17:03:33 INFO (SyncWorker_9) [pyupdate.ha_custom.custom_components] update_all: "['custom_updater', 'sensor.untappd']"
2018-10-02 17:03:34 INFO (SyncWorker_9) [pyupdate.ha_custom.custom_components] upgrade_single finished: "custom_updater"
2018-10-02 17:03:35 INFO (SyncWorker_9) [pyupdate.ha_custom.custom_components] upgrade_single finished: "sensor.untappd"
```
It logs a lot more with debug :D

Can you confirm that this works for you to before I close this one down?

**Comment by pnbruckner** [comment] 2018-10-02 15:10
It works, but the process requires updating (to get the new version of custom_updater), then a restart (to get the new version of pyupdate), then another update to finally get the component_urls update(s.)

**Comment by WildeRNS** [comment] 2018-10-02 15:12
> Can you confirm that this works for you to before I close this one down?

confirm - now works great!

**Comment by ludeeus** [comment] 2018-10-02 15:17
@pnbruckner That is the drawback of using external libs and custom components in general.
But it operates faster (if you use external lib), and with only one file to work with in homeassistant components it was a necessary step.

**Closed by ludeeus** 2018-10-02 15:17 UTC
Labels: Bug, Priority: high

**Comment by ludeeus** [comment] 2018-10-04 18:31
@pnbruckner look at the second `*` here :)
<https://github.com/custom-components/custom_updater/releases/tag/3.1.7>

**Comment by pnbruckner** [comment] 2018-10-04 20:00
Not quite sure why you did that. You have to restart to get the new version of custom_updater (or any custom component) to be used anyway, which will also update the requirements at the same time. How has the requirement to restart gone away? As I said, my comment wasn't valid. Sorry if I started you down an unnecessary path. Or am I missing something?

**Comment by ludeeus** [comment] 2018-10-04 20:11
If the component has external libs, the first time you start HA after adding/enabling it you usually get a "ModuleNotFoundError", a HA restart fixes that (and this version of custom_updater (if you use that to "install" it)) 
sometimes you could also get a "Could not find a version that satisfies the requirement" when upgrading (local pip cache not updated), this version handles that to.

**Comment by ludeeus** [comment] 2018-10-04 20:34
It does, but it does it at a later stage (so late that the component fails)

**Comment by pnbruckner** [comment] 2018-10-04 20:35
That sounds like a bug in HA then. Wouldn't it be better to get that fixed than to create workarounds? Or maybe it's more complicated than that.

**Comment by ludeeus** [comment] 2018-10-04 20:40
It's not a bug, it is how it works the loader would have to be rewritten for this.
